name: HCV

channels:
        - defaults
        - bioconda
        - conda-forge

dependencies:
        - bedtools=2.29.2
        - samtools=1.11
        - bcftools=1.11
        - trim-galore=0.6.6
        - r-base=4.0.3
        - pysam=0.16.0 # weeSAM dependency
        - matplotlib=3.3.3 # weeSAM dependency
        - seaborn=0.11.1 # weeSAM dependency
        - seqkit=0.14.0
        - bowtie2=2.4.2

# Additional dependencies not installed using conda
# Tanoti v1.2 (https://bioinformatics.cvr.ac.uk/software/tanoti/)
# weeSAM v1.5 (https://bioinformatics.cvr.ac.uk/weesam-version-1-5/)
