name: GATK 

channels:
        - defaults
        - bioconda
        - conda-forge

dependencies:
        - bwa=0.7.17
        - gatk4=4.1.9.0
        - samtools=1.11
        - bedtools=2.29.2
        - r-base=4.0.3
        - seqkit=0.14.0
        - bcftools=1.11
